# Generated by Django 4.0.4 on 2023-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Все вещи ', 'verbose_name_plural': 'Вещи '},
        ),
    ]
